### ISSUE TITLE
TypeError: The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by jomarquez21** [swordev/phpstan-vscode#25]
I get an error with this `phpstan.neon.dist` configuration:
```
includes:
    - phpstan-baseline.neon

parameters:
    level: 5
    paths:
        - src
        - tests
    treatPhpDocTypesAsCertain: false
    checkGenericClassInNonGenericObjectType: true
    checkMissingIterableValueType: true
    checkMissingVarTagTypehint: true
    checkMissingTypehints: true
```
